# Configuration
config:
  heading-increment: false
  no-alt-text: false
  no-duplicate-heading: false
  # MD013 - line-length
  line_length:
    line_length: 120
    code_blocks: false
    tables: false
  html:
    allowed_elements:
      - div

globs:
  - "**/*.md"
  - "**/*.qmd"

ignore:
  - ".quarto/**/*.md"
  - "_site/**/*.md"
  - "_site/site_libs/revealjs/plugin/reveal-chalkboard/*.md"
  - "renv/**/*.md"

# Fix any fixable errors
fix: true
