project:
  type: website

website:
  title: "PCC - WhatsApp or Signal"
  site-url: https://slackline.github.io/pcc-signal
  description: "Summary of the pros and cons of switching from WhatsApp to Signal for communication between members of the Peak Climbing Club"
